//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatPlanet.JosePauloAntazo.MVCApp.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter
    {
        public int ID { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
